import { Team } from "./team-interface";

export const TEAMS: Team[] = [
  { name: "Boston Red Sox", abbreviation: "BOS", logo: "https://loodibee.com/wp-content/uploads/mlb-boston-red-sox-logo.png" },
  { name: "Baltimore Orioles", abbreviation: "BAL", logo: "https://loodibee.com/wp-content/uploads/mlb-baltimore-orioles-logo.png" },
  { name: "Chicago White Sox", abbreviation: "CHW", logo: "https://loodibee.com/wp-content/uploads/mlb-chicago-white-sox-logo.png" },
  { name: "Cleveland Guardians", abbreviation: "CLE", logo: "https://loodibee.com/wp-content/uploads/mlb-cleveland-guardians-logo.png" },
  { name: "Detroit Tigers", abbreviation: "DET", logo: "https://loodibee.com/wp-content/uploads/mlb-detroit-tigers-logo.png" },
  { name: "Houston Astros", abbreviation: "HOU", logo: "https://loodibee.com/wp-content/uploads/mlb-Houston-Astros-Logo.png" },
  { name: "Kansas City Royals", abbreviation: "KC", logo: "https://loodibee.com/wp-content/uploads/mlb-kansas-city-royals-logo.png" },
  { name: "Los Angeles Angels", abbreviation: "LAA", logo: "https://loodibee.com/wp-content/uploads/mlb-los-angeles-angels-logo.png" },
  { name: "Minnesota Twins", abbreviation: "MIN", logo: "https://loodibee.com/wp-content/uploads/mlb-minnesota-twins-logo.png" },
  { name: "New York Yankees", abbreviation: "NYY", logo: "https://loodibee.com/wp-content/uploads/mlb-new-york-yankees-logo.png" },
  { name: "Oakland Athletics", abbreviation: "OAK", logo: "https://loodibee.com/wp-content/uploads/mlb-oakland-athletics-logo.png" },
  { name: "Seattle Mariners", abbreviation: "SEA", logo: "https://loodibee.com/wp-content/uploads/mlb-seattle-mariners-logo.png" },
  { name: "Tampa Bay Rays", abbreviation: "TB", logo: "https://loodibee.com/wp-content/uploads/mlb-tampa-bay-rays-logo.png" },
  { name: "Texas Rangers", abbreviation: "TEX", logo: "https://loodibee.com/wp-content/uploads/mlb-texas-rangers-logo.png" },
  { name: "Toronto Blue Jays", abbreviation: "TOR", logo: "https://loodibee.com/wp-content/uploads/mlb-toronto-blue-jays-logo.png" },
  { name: "Arizona Diamondbacks", abbreviation: "ARI", logo: "https://loodibee.com/wp-content/uploads/mlb-arizona-diamondbacks-logo.png" },
  { name: "Atlanta Braves", abbreviation: "ATL", logo: "https://loodibee.com/wp-content/uploads/mlb-atlanta-braves-logo.png" },
  { name: "Chicago Cubs", abbreviation: "CHC", logo: "https://loodibee.com/wp-content/uploads/mlb-chicago-cubs-logo.png" },
  { name: "Cincinnati Reds", abbreviation: "CIN", logo: "https://loodibee.com/wp-content/uploads/mlb-cincinnati-reds-logo.png" },
  { name: "Colorado Rockies", abbreviation: "COL", logo: "https://loodibee.com/wp-content/uploads/mlb-colorado-rockies-logo.png" },
  { name: "Los Angeles Dodgers", abbreviation: "LAD", logo: "https://loodibee.com/wp-content/uploads/mlb-los-angeles-dodgers-logo.png" },
  { name: "Miami Marlins", abbreviation: "MIA", logo: "https://loodibee.com/wp-content/uploads/mlb-miami-marlins-logo.png" },
  { name: "Milwaukee Brewers", abbreviation: "MIL", logo: "https://loodibee.com/wp-content/uploads/mlb-milwaukee-brewers-logo.png" },
  { name: "New York Mets", abbreviation: "NYM", logo: "https://loodibee.com/wp-content/uploads/mlb-new-york-mets-logo.png" },
  { name: "Philadelphia Phillies", abbreviation: "PHI", logo: "https://loodibee.com/wp-content/uploads/mlb-Philadelphia-Phillies-Logo.png" },
  { name: "Pittsburgh Pirates", abbreviation: "PIT", logo: "https://loodibee.com/wp-content/uploads/mlb-pittsburgh-pirates-logo.png" },
  { name: "San Diego Padres", abbreviation: "SD", logo: "https://loodibee.com/wp-content/uploads/mlb-san-diego-padres-logo.png" },
  { name: "San Francisco Giants", abbreviation: "SF", logo: "https://loodibee.com/wp-content/uploads/mlb-san-francisco-giants-logo.png" },
  { name: "St. Louis Cardinals", abbreviation: "STL", logo: "https://loodibee.com/wp-content/uploads/mlb-st-louis-cardinals-logo.png" },
  { name: "Washington Nationals", abbreviation: "WSH", logo: "https://loodibee.com/wp-content/uploads/mlb-Washington-Nationals-Logo.png" }
];
