import { Team } from "./team-interface";

export const TEAMS: Team[] = [
  { name: "Boston Red Sox", abbreviation: "BOS", logo: "https://content.sportslogos.net/logos/53/53/full/boston_red_sox_logo_primary_20097510.png" },
  { name: "Baltimore Orioles", abbreviation: "BAL", logo: "https://content.sportslogos.net/logos/53/52/full/baltimore_orioles_logo_primary_20195398.png" },
  { name: "Chicago White Sox", abbreviation: "CHW", logo: "https://content.sportslogos.net/logos/53/55/full/chicago_white_sox_logo_primary_19911413.png" },
  { name: "Cleveland Guardians", abbreviation: "CLE", logo: "https://content.sportslogos.net/logos/53/6804/full/cleveland_guardians_logo_primary_2022_sportslogosnet-5538.png" },
  { name: "Detroit Tigers", abbreviation: "DET", logo: "https://content.sportslogos.net/logos/53/59/full/detroit_tigers_logo_primary_20162109.png" },
  { name: "Houston Astros", abbreviation: "HOU", logo: "https://content.sportslogos.net/logos/53/4929/full/houston_astros_logo_primary_20137038.png" },
  { name: "Kansas City Royals", abbreviation: "KC", logo: "https://content.sportslogos.net/logos/53/62/full/kansas_city_royals_logo_primary_20198736.png" },
  { name: "Los Angeles Angels", abbreviation: "LAA", logo: "https://content.sportslogos.net/logos/53/6521/full/4389_los_angeles_angels-primary-2016.png" },
  { name: "Minnesota Twins", abbreviation: "MIN", logo: "https://content.sportslogos.net/logos/53/65/full/minnesota_twins_logo_primary_2023_sportslogosnet-3953.png" },
  { name: "New York Yankees", abbreviation: "NYY", logo: "https://content.sportslogos.net/logos/53/68/full/1256.png" },
  { name: "Oakland Athletics", abbreviation: "OAK", logo: "https://content.sportslogos.net/logos/53/69/full/6xk2lpc36146pbg2kydf13e50.png" },
  { name: "Seattle Mariners", abbreviation: "SEA", logo: "https://content.sportslogos.net/logos/53/75/full/seattle_mariners_logo_primary_19933809.png" },
  { name: "Tampa Bay Rays", abbreviation: "TB", logo: "https://content.sportslogos.net/logos/53/2535/full/tampa_bay_rays_logo_primary_20196768.png" },
  { name: "Texas Rangers", abbreviation: "TEX", logo: "https://content.sportslogos.net/logos/53/77/full/ajfeh4oqeealq37er15r3673h.png" },
  { name: "Toronto Blue Jays", abbreviation: "TOR", logo: "https://content.sportslogos.net/logos/53/78/full/8987_toronto_blue_jays-primary-2020.png" },
  { name: "Arizona Diamondbacks", abbreviation: "ARI", logo: "https://content.sportslogos.net/logos/54/50/full/arizona_diamondbacks_logo_primary_20123733.png" },
  { name: "Atlanta Braves", abbreviation: "ATL", logo: "https://content.sportslogos.net/logos/54/51/full/3kgwjp6heowkeg3w8zoow9ggy.png" },
  { name: "Chicago Cubs", abbreviation: "CHC", logo:"https://content.sportslogos.net/logos/54/54/full/chicago_cubs_logo_primary_19792956.png" },
  { name: "Cincinnati Reds", abbreviation: "CIN", logo: "https://content.sportslogos.net/logos/54/56/full/cincinnati_reds_logo_primary_20133208.png" },
  { name: "Colorado Rockies", abbreviation: "COL", logo: "https://content.sportslogos.net/logos/54/58/full/colorado_rockies_logo_primary_20171892.png" },
  { name: "Los Angeles Dodgers", abbreviation: "LAD", logo: "https://content.sportslogos.net/logos/54/63/full/los_angeles_dodgers_logo_primary_20127886.png" },
  { name: "Miami Marlins", abbreviation: "MIA", logo: "https://content.sportslogos.net/logos/54/3637/full/7544_miami_marlins-primary-2019.png" },
  { name: "Milwaukee Brewers", abbreviation: "MIL", logo: "https://content.sportslogos.net/logos/54/64/full/6474_milwaukee_brewers-primary-2020.png" },
  { name: "New York Mets", abbreviation: "NYM", logo: "https://content.sportslogos.net/logos/54/67/full/m01gfgeorgvbfw15fy04alujm.png" },
  { name: "Philadelphia Phillies", abbreviation: "PHI", logo: "https://content.sportslogos.net/logos/54/70/full/philadelphia_phillies_logo_primary_20193931.png" },
  { name: "Pittsburgh Pirates", abbreviation: "PIT", logo: "https://content.sportslogos.net/logos/54/71/full/1250_pittsburgh_pirates-primary-2014.png" },
  { name: "San Diego Padres", abbreviation: "SD", logo: "https://content.sportslogos.net/logos/54/73/full/7517_san_diego_padres-primary-2020.png" },
  { name: "San Francisco Giants", abbreviation: "SF", logo: "https://content.sportslogos.net/logos/54/74/full/san_francisco_giants_logo_primary_20002208.png" },
  { name: "St. Louis Cardinals", abbreviation: "STL", logo: "https://content.sportslogos.net/logos/54/72/full/3zhma0aeq17tktge1huh7yok5.png" },
  { name: "Washington Nationals", abbreviation: "WSH", logo: "https://content.sportslogos.net/logos/54/578/full/rcehah9k0kekjkgzm077fflws.png" }
];
